theme = "catppuccin_frappe"

[editor.cursor-shape]
insert = "bar"

[keys.normal]
C-right = "move_next_word_start"
C-left = "move_prev_word_end"
C-f = "search"
"/" = "command_mode"
C-v = "paste_clipboard_after"
C-c = "yank_to_clipboard"
C-z = "undo"
C-S-z = "redo"

[keys.insert]
C-right = "move_next_word_start"
C-left = "move_prev_word_end"
C-f = "search"
C-v = "paste_clipboard_after"
C-c = "yank_to_clipboard"
C-z = "undo"
C-S-z = "redo"

[keys.select]
C-v = "paste_clipboard_after"
C-c = "yank_to_clipboard"
C-z = "undo"
C-S-z = "redo"
